### ISSUE TITLE
OS X make problem

### ISSUE THREAD

**Issue by doffen** [anthonix/ffts#68]
Any suggestions on how to get ffts to build on my Mac?  I have Mac OS 10.13.4 with Xcode 9.3, I run:
./configure --enable-sse --enable-single --prefix=/usr/local

"configure" seems to work OK with this warning (which may or may not be significant):
/Users/dave/Documents/ffts-master/missing: Unknown '--is-lightweight' option
Try '/Users/dave/Documents/ffts-master/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing

Then, when I type "make" I initially get this error:
ffts.c:34:10: fatal error: 'ffts.h' file not found

So I copy ffts.h from the include to the src directory, rerun "make" and then get this output with several warnings and errors indicating missing or incorrect C include files:
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT ffts.lo -MD -MP -MF .deps/ffts.Tpo -c -o ffts.lo ffts.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -g -O2 -MT ffts.lo -MD -MP -MF .deps/ffts.Tpo -c ffts.c -o ffts.o
In file included from ffts.c:36:
./ffts_internal.h:227:9: warning: implicitly declaring library function 'malloc'
      with type 'void *(unsigned long)' [-Wimplicit-function-declaration]
    p = malloc(size);
        ^
./ffts_internal.h:227:9: note: include the header <stdlib.h> or explicitly
      provide a declaration for 'malloc'
./ffts_internal.h:249:5: warning: implicit declaration of function 'free' is
      invalid in C99 [-Wimplicit-function-declaration]
    free(p);
    ^
In file included from ffts.c:40:
In file included from ./macros.h:49:
./macros-alpha.h:58:5: error: unknown type name 'uint32_t'
    uint32_t u[4];

**Comment by linkotec** [comment]
Use CMake to build FFTS, we have not maintained AutoConf for long time

**Comment by Unitrunker** [comment]
Wow. Good to know. Please update the readme.
